[build]
target = "index.html"
release = false
dist = "dist"
public_url = "https://frostu8.github.io/citrus/"

[watch]
path = ["src", "web"]
ignore = []

[serve]
port = 8080
open = true

[clean]
dist = "dist"
cargo = false
