name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # check out git files
    - uses: actions/checkout@v2

    # setup rust
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        target: wasm32-unknown-unknown
        toolchain: nightly
        override: true

    - name: Install wasm-bindgen-cli
      uses: actions-rs/install@v0.1
      with:
        crate: wasm-bindgen-cli
        version: latest
        use-tool-cache: true

    - name: Install wasm-pack
      uses: actions-rs/install@v0.1
      with:
        crate: wasm-pack
        version: latest
        use-tool-cache: true

    - name: Install trunk
      uses: actions-rs/install@v0.1
      with:
        crate: trunk
        version: latest
        use-tool-cache: true

    # build server
    - name: Build
      run: trunk build

    # deploy
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
